application: spark-prs
version: 3
runtime: python27
api_version: 1
threadsafe: yes
default_expiration: 1m

handlers:
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico
- url: /gae_mini_profiler/static
  static_dir: gae_mini_profiler/static
- url: /gae_mini_profiler/.*
  script: gae_mini_profiler.main.application
- url: /static
  static_dir: static
- url: /tasks/.*  # Require admin access for cron tasks (to prevent rate-limit violations)
  script: main.app
  secure: always
  login: admin
- url: .*  # Route all requets to the WSGI application
  script: main.app
  secure: always

builtins:
- appstats: on

libraries:
- name: ssl
  version: latest

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^node_modules/.*$
- ^gae_mini_profiler/.*$
