"""Create initial database

Revision ID: 5657bde4290b
Revises: 
Create Date: 2014-12-22 22:48:11.287842

"""

# revision identifiers, used by Alembic.
revision = '5657bde4290b'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils import JSONType



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_username', sa.String(length=128), nullable=False),
    sa.Column('github_access_token', sa.String(length=128), nullable=True),
    sa.Column('github_json', JSONType(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('avatar_url', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_username'),
    sa.UniqueConstraint('id')
    )
    op.create_table('jira_issue',
    sa.Column('issue_id', sa.String(length=64), nullable=False),
    sa.Column('issue_json', JSONType(), nullable=False),
    sa.PrimaryKeyConstraint('issue_id')
    )
    op.create_table('pull_request',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('pr_json', JSONType(), nullable=False),
    sa.Column('files_json', JSONType(), nullable=True),
    sa.Column('pr_json_etag', sa.String(length=128), nullable=True),
    sa.Column('pr_comments_etag', sa.String(length=128), nullable=True),
    sa.Column('pr_review_comments_etag', sa.String(length=128), nullable=True),
    sa.Column('pr_files_json_etag', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('number'),
    sa.UniqueConstraint('number')
    )
    op.create_table('prs_jiras',
    sa.Column('fk_jira', sa.String(length=64), nullable=True),
    sa.Column('fk_pull_request', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_jira'], ['jira_issue.issue_id'], ),
    sa.ForeignKeyConstraint(['fk_pull_request'], ['pull_request.number'], )
    )
    op.create_table('review_comment',
    sa.Column('pr', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('body', sa.UnicodeText(), nullable=False),
    sa.Column('diff_hunk', sa.UnicodeText(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['pr'], ['pull_request.number'], ),
    sa.PrimaryKeyConstraint('pr', 'id')
    )
    op.create_table('issue_comment',
    sa.Column('pr', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('body', sa.UnicodeText(), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['pr'], ['pull_request.number'], ),
    sa.PrimaryKeyConstraint('pr', 'id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issue_comment')
    op.drop_table('review_comment')
    op.drop_table('prs_jiras')
    op.drop_table('pull_request')
    op.drop_table('jira_issue')
    op.drop_table('user')
    ### end Alembic commands ###
