"""Changed nullability of jira_issue.issue_json

Revision ID: 56b17e242cb9
Revises: 5657bde4290b
Create Date: 2014-12-22 22:51:14.943329

"""

# revision identifiers, used by Alembic.
revision = '56b17e242cb9'
down_revision = '5657bde4290b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jira_issue', 'issue_json',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.add_column('review_comment', sa.Column('creation_time', sa.DateTime(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_comment', 'creation_time')
    op.alter_column('jira_issue', 'issue_json',
               existing_type=mysql.TEXT(),
               nullable=False)
    ### end Alembic commands ###
